import { DM_Sans, Figtree } from "next/font/google";
import "@/src/assets/styles/globals.css";
import Header from "@/src/components/Header";
import "animate.css";
import { ScrollToTop } from "@/src/components/ScrollToTop";

// FONTS
const dm_sans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  display: "swap",
  variable: "--font-figtree",
});

// Metada
export const metadata = {
  title: "Dash & Dry",
  description: "Generated by create next app",
};

export default function LocaleLayout({ children, params: { locale } }) {
  // Aarray of objects storing the URL nks + text
  const links = [
    { to: "/", text: "Home" },
    { to: "/washing-solutions", text: "Washing Solutions" },
    { to: "/our-location", text: "Our Location" },
    { to: "/about-us", text: "About Us" },
    { to: "/contact", text: "Contact" },
  ];

  return (
    <html lang={locale} className={`${dm_sans.variable} ${figtree.variable}`}>
      <body>
        <ScrollToTop />
        <Header links={links} />
        <main>{children}</main>
      </body>
    </html>
  );
}
